<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>SmolBit</string>
	<key>scopeName</key>
	<string>source.smolbit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.smolbit</string>
			<key>match</key>
			<string>;([\s|\S]*);</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.smolbit</string>
			<key>match</key>
			<string>[^\(\)a-fABCXYZ0-9@&amp;%|huxEDHijkl\+\-\=\*\/\^v&gt;&lt;_~#\?\[\]RFVUSLW;\s\t\n\r]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>invalid.illegal.smolbit</string>
			<key>match</key>
			<string>[0-9a-f]{3,}</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([FS])\s?([0-9a-f])</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.smolbit</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.smolbit</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.smolbit</string>
			<key>match</key>
			<string>[\?RFVUSLW\[\]\)\(]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.smolbit</string>
			<key>match</key>
			<string>[\+\-\=\*\/\^v&gt;&lt;_~#]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.comparison.smolbit</string>
			<key>match</key>
			<string>[ijkl]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric.smolbit</string>
			<key>match</key>
			<string>([0-9a-f]{2})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.variable.smolbit</string>
			<key>match</key>
			<string>([0-9a-e]{1})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.variable.global.smolbit</string>
			<key>match</key>
			<string>([f]{1})</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.smolbit</string>
			<key>match</key>
			<string>[@ABCXYZ&amp;]</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.smolbit</string>
			<key>match</key>
			<string>[|%huxEDH.]</string>
		</dict>
	</array>
</dict>
</plist>